x-redis-common: &redis-common
  REDIS_HOST: redis:6379
  REDIS_PORT: 6379
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""
  REDIS_DB: 0
  REDIS_PROTOCOL: 2

x-config-volume: &config-volume
  volumes:
    - ./config.prod.yaml:/app/config.prod.yaml

networks:
  app-network:
    driver: bridge

services:
  # proxy:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   volumes:
  #     - ./config/gateway/:/etc/nginx/conf.d/:ro
  #     - ./config/certbot/:/etc/letsencrypt:ro
  #     - ./www/certbot/:/var/www/certbot/:ro
  #     - ./content/object.patchwork.horse/:/var/www/object.patchwork.horse/:ro
  #   networks:
  #     - app-network

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./www/certbot/:/var/www/certbot/:rw
  #     - ./config/certbot/:/etc/letsencrypt/:rw
  #   networks:
  #     - app-network
  
  api:
    <<: *config-volume
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      <<: *redis-common
      GIN_MODE: release
      BUCKETD_CORE__MODE: http
    restart: unless-stopped

  dns:
    <<: *config-volume
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53:8053/udp"
    networks:
      - app-network
    environment:
      <<: *redis-common
      BUCKETD_CORE__MODE: dns
    restart: unless-stopped

  redis: 
    image: "redis:latest"
    networks:
      - app-network
    ports:
      - "6379:6379"
    restart: unless-stopped